<a href="https://colab.research.google.com/github/DPKamalnayan/DPKamalnayan.github.io/blob/main/kagglePandasLibExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [263]:
'''
import pandas as pd

#save the filepath to variabel for easier access
melbourne_file_path = 'melbourne_housing_data.csv'
#or melbourne_file_path = '/content/melbourne_housing_data.csv'

#read the data and store data in DataFrame titled melnourne_data
melbourne_data = pd.read_csv(melbourne_file_path)

#print a summary of the data in melbourne data
melbourne_data.describe()
'''

"\nimport pandas as pd\n\n#save the filepath to variabel for easier access\nmelbourne_file_path = 'melbourne_housing_data.csv'\n#or melbourne_file_path = '/content/melbourne_housing_data.csv'\n\n#read the data and store data in DataFrame titled melnourne_data\nmelbourne_data = pd.read_csv(melbourne_file_path)\n\n#print a summary of the data in melbourne data\nmelbourne_data.describe()\n"

**Interpreting Data**

The results 8 numbers for each column in your original dataset. The first number, the **count,** shows how many rows have non-missing values.

Missing values arise for many reasons. Gor example, the size of the 2nd bedroom wouldn't be collected when surveying a 1 bedroom house.

The second value is the **mean,** which is the average. Under the, **std** is the standard deviation, which measures how numerically spread out the values are.

To interpret the **min, 25%, 50%, 75%** and **max** values, imagine sorting each column from lowest to highest value. The first(smallest) value is the min. If you go a quarter way through the list, you'll find a number that is bigger than 25% of the values and smaller than 75% of the values. That is the **25%** value(pronounced "25th percentile"). The 50th and 75th percentiles are defined analogously, and the **max** is the largest number.

In [264]:
'''
import pandas as pd
#a dataframe is the main datastructure and is a table like structure with additional fuctionality.
#df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
#df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'])
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'], index=['x','y','z'])

#df.head()
#df.head(2)

#df.tail()
#df.tail(2)
#df.columns
#df.index
#df.index.tolist()
#df.info()
#df.describe()

#to find number of unique values in columns
#df.nunique()
#for specific column
#df['a'].nunique()

#to find the shape of dataframe
#df.shape

#to find total number of items
#df.size
'''

"\nimport pandas as pd\n#a dataframe is the main datastructure and is a table like structure with additional fuctionality.\n#df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])\n#df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'])\ndf = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'], index=['x','y','z'])\n\n#df.head()\n#df.head(2)\n\n#df.tail()\n#df.tail(2)\n#df.columns\n#df.index\n#df.index.tolist()\n#df.info()\n#df.describe()\n\n#to find number of unique values in columns\n#df.nunique()\n#for specific column\n#df['a'].nunique()\n\n#to find the shape of dataframe\n#df.shape\n\n#to find total number of items\n#df.size\n"

In [265]:
'''
#Loading in Dataframes form files
import pandas as pd

#loading simple csv data(csv is readable format but is large size file)
#df = pd.read_csv('/content/warmup_data/coffee.csv')
#using raw url data directly
#df = pd.read_csv('https://raw.githubusercontent.com/DPKamalnayan/DPKamalnayan.github.io/refs/heads/main/warmup-data/coffee.csv')

#loading parquet
#df = pd.read_parquet('/content/data/results.parquet')

#loading excel
#dfe = pd.read_excel('/content/data/olympics-data.xlsx')
dfe = pd.read_excel('/content/data/olympics-data.xlsx', sheet_name ="results")

dfe.head()
'''

'\n#Loading in Dataframes form files\nimport pandas as pd\n\n#loading simple csv data(csv is readable format but is large size file)\n#df = pd.read_csv(\'/content/warmup_data/coffee.csv\')\n#using raw url data directly\n#df = pd.read_csv(\'https://raw.githubusercontent.com/DPKamalnayan/DPKamalnayan.github.io/refs/heads/main/warmup-data/coffee.csv\')\n\n#loading parquet\n#df = pd.read_parquet(\'/content/data/results.parquet\')\n\n#loading excel\n#dfe = pd.read_excel(\'/content/data/olympics-data.xlsx\')\ndfe = pd.read_excel(\'/content/data/olympics-data.xlsx\', sheet_name ="results")\n\ndfe.head()\n'

In [266]:
import pandas as pd

coffee = pd.read_csv('/content/warmup_data/coffee.csv')
results = pd.read_parquet('/content/data/results.parquet')
bios = pd.read_csv('/content/data/bios.csv')

bios.to_parquet

bios.to_feather

results.to_csv

results.to_excel

can be applied to resave dataframe in that format.

In [267]:
coffee.loc[5:8,["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [268]:
#Accessing data with pandas

#to access random data sample
#coffee.sample(10)
#add randomstate to make data deterministic
#coffee.sample(10,random_state=1)

#to access specific values
#coffee.loc(#Rows,#colums)
#coffee.loc[0]
#coffee.loc[[0,1,5]]
#coffee.loc[1:5]
#coffee.loc[0:10:2]
#coffee.loc[3:10, ["Day","Units Sold"]]
#coffee.loc[5:8,["Day","Units Sold"]]

#coffee.iloc[0:5,[0,2]]

#coffee.index = coffee["Day"]
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [269]:
#Accessing Data with Pandas

# loc & iloc
#lov allows us to filter data by rows and columns
#coffe.loc[#Rows, #columns]

#coffee.loc[0]
#coffee.loc[[0,1,2]]
#coffee.loc[[0,1,5]]
#the slice syntax is permitted.
#coffee.loc[5:]
#coffee.loc[5:12]
#coffee.loc[5:8,["Day", "Units Sold"]]
#coffee.loc[:,["Day", "Units Sold"]]



#iloc uses indexlocations instead of labels

#coffee.iloc[:,[0,2]]
#coffee.iloc[0:5,[0,2]]
# upper index is not inclusive in .iloc, while upper index is inclusive in loc

#coffee.index= coffee.Day
#or
#coffee.index = coffee["Day"]
#coffee.loc["Monday":"Wednesday"]
#coffee.loc["Monday":"Wednesday",["Day","Units Sold"]]


#to set a specific value
#coffee.loc[1,"Units Sold"] = 10
#coffee.loc[1:3,"Units Sold"] = 10

#coffee

# .iat and .at are optimised way of fetching single specific values.
# coffee.at[0:5,"Units Sold"] or coffee.iat[0,"Units Sold"] is wrong

#coffee.at[0,"Units Sold"]
#coffee.iat[0,0]

#To grab column
#coffee["Day"]
#or if single word no space
#coffee.Day
#coffee["Units Sold"]

#To fetch data in sorted form
#accending order
#coffee.sort_values("Units Sold")
#for decneding order
#coffee.sort_values(["Units Sold","Coffee Type"],ascending=[0,1])

#to itterate through row by row
'''
for index, row in coffee.iterrows():
  print(index)
  print(row)
  print(row['Coffee Type'])
  print('\n\n\n\n')
'''

"\nfor index, row in coffee.iterrows():\n  print(index)\n  print(row)\n  print(row['Coffee Type'])\n  print('\n\n\n\n')\n"

In [270]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [271]:
'''
#Filtering Data

#bios.head()
#bios.tail()
#bios.info()

bios.loc[bios['height_cm'] > 215,]
bios.loc[bios['height_cm'] > 215,['name','height_cm']]
bios[bios['height_cm'] > 215]
#short hand
bios[bios['height_cm'] > 215][['name','height_cm']]
#multipule filters
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')][['born_country','name','height_cm']]

bios.loc[bios['name'].str.contains("Keith")]  # .str methord get the string properties of the datafreame feild and .contains methord
# RegEx syntax is applicable and very important
bios.loc[bios['name'].str.contains("Keith", case=False)]
#bios.loc[bios['name'].str.contains("Keith|patrick", case=False, na=False)]

bios[bios['born_country'] == 'IND']

bios[bios['born_country'].isin(["IND","FRA"])]

bios[bios['born_country'].isin(["IND","FRA","USA"]) & (bios['name'].str.startswith("Keith"))]
bios.query('born_country == "IND" and born_city == "Lucknow"')

'''
#https://www.w3schools.com/python/python_regex.asp

'\n#Filtering Data\n\n#bios.head()\n#bios.tail()\n#bios.info()\n\nbios.loc[bios[\'height_cm\'] > 215,]\nbios.loc[bios[\'height_cm\'] > 215,[\'name\',\'height_cm\']]\nbios[bios[\'height_cm\'] > 215]\n#short hand\nbios[bios[\'height_cm\'] > 215][[\'name\',\'height_cm\']]\n#multipule filters\nbios[(bios[\'height_cm\'] > 215) & (bios[\'born_country\'] == \'USA\')]\nbios[(bios[\'height_cm\'] > 215) & (bios[\'born_country\'] == \'USA\')][[\'born_country\',\'name\',\'height_cm\']]\n\nbios.loc[bios[\'name\'].str.contains("Keith")]  # .str methord get the string properties of the datafreame feild and .contains methord\n# RegEx syntax is applicable and very important\nbios.loc[bios[\'name\'].str.contains("Keith", case=False)]\n#bios.loc[bios[\'name\'].str.contains("Keith|patrick", case=False, na=False)]\n\nbios[bios[\'born_country\'] == \'IND\']\n\nbios[bios[\'born_country\'].isin(["IND","FRA"])]\n\nbios[bios[\'born_country\'].isin(["IND","FRA","USA"]) & (bios[\'name\'].str.startswith("Keith"))]\nbios.query(\'born_country == "IND" and born_city == "Lucknow"\')\n\n'

In [272]:
print(bios)
bios.info()
bios.describe()

        athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date
0       1960-10-02
1              NaN
2       1994-07-17
3       1978-03-20
4       1930-07-25
...            ...
145495         NaN
145496         NaN
145497         NaN
145498  1986-03-18
145499  2003-10-20

[145500 rows x 10 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

          athlete_id      height_cm      weight_kg
count  145500.000000  106651.000000  102070.000000
mean    73686.188955     176.333724      71.890996
std     42868.960158      10.380282      14.465540
min         1.000000     127.000000      25.000000
25%     36663.750000     170.000000      62.000000
50%     73302.500000     176.000000      70.000000
75%    110306.250000     183.000000      80.000000
max    149814.000000     226.000000     198.000000

In [273]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [274]:
#Adding and Removing columns
coffee['price'] = 4.99
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [275]:
#dropping the price columns
#coffee = coffee.drop(columns=['price'])
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [276]:
import numpy as np

coffee['new_price'] = np.where(coffee['Coffee Type'] =='Espresso', 3.99, 5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [277]:
#to select only specific columns and not select price

#coffee= coffee[['Day','Coffee Type','Units Sold','new_price']]
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [278]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee

          Day Coffee Type  Units Sold  price  new_price  revenue
0      Monday    Espresso          25   4.99       3.99    99.75
1      Monday       Latte          15   4.99       5.99    89.85
2     Tuesday    Espresso          30   4.99       3.99   119.70
3     Tuesday       Latte          20   4.99       5.99   119.80
4   Wednesday    Espresso          35   4.99       3.99   139.65
5   Wednesday       Latte          25   4.99       5.99   149.75
6    Thursday    Espresso          40   4.99       3.99   159.60
7    Thursday       Latte          30   4.99       5.99   179.70
8      Friday    Espresso          45   4.99       3.99   179.55
9      Friday       Latte          35   4.99       5.99   209.65
10   Saturday    Espresso          45   4.99       3.99   179.55
11   Saturday       Latte          35   4.99       5.99   209.65
12     Sunday    Espresso          45   4.99       3.99   179.55
13     Sunday       Latte          35   4.99       5.99   209.65

In [279]:
coffee.rename(columns={'new_price':'price'}, inplace=True)

In [280]:
bios_new = bios.copy()
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [281]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB

In [282]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB

In [283]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [284]:
#to save the updated bios new dataframe
#use index = flase to not save extra column, because pandas was built with
#backwards compatibility the extra colums is saved

bios_new.to_parquet('/content/data/bios_new.parquet', index=False)

In [285]:
bios_new.query('first_name == "Keith"')
#bios_new.loc[bios_new['first_name'] == 'Keith']

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith,1966-09-01,1966.0
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,1961-03-29,1961.0
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith,1940-10-15,1940.0
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith,1966-01-01,1966.0
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,1898-11-03,1898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,1970-02-03,1970.0
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith,1983-02-09,1983.0
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith,1927-08-25,1927.0
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,1975-02-02,1975.0
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith,1979-09-07,1979.0

In [286]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x <185 else 'Tall'))
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall

In [287]:
def categorize_athlete(row):
  if row['height_cm'] < 175 and row['weight_kg'] < 70:
    return 'Lightweight'
  elif row['height_cm'] <185 or row['weight_kg'] <=80:
    return 'Midweight'
  else:
    return 'Heavyweight'

bios_new['athlete_category'] = bios_new.apply(categorize_athlete, axis=1)#axis=1 for rows and 0 for columns
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,athlete_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Midweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Midweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Average,Lightweight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Average,Lightweight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short,Lightweight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Average,Midweight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall,Heavyweight

In [288]:
#bios.loc[bios['born_country'] == 'IND' ]
Ind_bios = bios[bios['born_country'] == 'IND'].copy()
Ind_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
...,...,...,...,...,...,...,...,...,...,...
140286,143790,Bajrang Punia,1994-02-26,Khudan,Haryana,IND,India,NaN,NaN,NaN
140287,143791,Deepak Punia,1999-05-19,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN
144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN

In [289]:
Ind_bios = bios[bios['born_country'] == 'IND']
Ind_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
...,...,...,...,...,...,...,...,...,...,...
140286,143790,Bajrang Punia,1994-02-26,Khudan,Haryana,IND,India,NaN,NaN,NaN
140287,143791,Deepak Punia,1999-05-19,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN
144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN

In [290]:
FRA_bios = bios.loc[bios['born_country'] == 'FRA']
FRA_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144652,148348,James Clugnet,1996-12-04,Grenoble,Isère,FRA,Great Britain,NaN,NaN,NaN
145009,148720,Margaux Hackett,1999-06-02,Annecy,Haute-Savoie,FRA,New Zealand,NaN,NaN,NaN
145281,149002,Elliott Baralo,1998-08-01,Annecy,Haute-Savoie,FRA,Sweden,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [291]:
#this drop command(without assingment) does not modify the dataframe just returns a modifies virsion
#coffee.drop(0)
#coffee.drop(columns=['price'])

#to actually modify the dataframe
#coffee.drop(columns=['price'], inplace=True)

In [292]:
coffee_new = coffee
coffee_new['price'] = 4.99
# any changes to coffee_new will also change coffee because the both point to the same dataframe

In [293]:
#to make separate copy of a dataframe
coffee_new = coffee.copy()
coffee_new['price'] = 4.99

In [294]:
print(coffee_new,'\n\n\n',coffee)

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso          25   4.99   4.99    99.75
1      Monday       Latte          15   4.99   4.99    89.85
2     Tuesday    Espresso          30   4.99   4.99   119.70
3     Tuesday       Latte          20   4.99   4.99   119.80
4   Wednesday    Espresso          35   4.99   4.99   139.65
5   Wednesday       Latte          25   4.99   4.99   149.75
6    Thursday    Espresso          40   4.99   4.99   159.60
7    Thursday       Latte          30   4.99   4.99   179.70
8      Friday    Espresso          45   4.99   4.99   179.55
9      Friday       Latte          35   4.99   4.99   209.65
10   Saturday    Espresso          45   4.99   4.99   179.55
11   Saturday       Latte          35   4.99   4.99   209.65
12     Sunday    Espresso          45   4.99   4.99   179.55
13     Sunday       Latte          35   4.99   4.99   209.65


           Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso          25   4.99   4.99    99.75
1      Monday       Latte          15   4.99   4.99    89.85
2     Tuesday    Espresso          30   4.99   4.99   119.70
3     Tuesday       Latte          20   4.99   4.99   119.80
4   Wednesday    Espresso          35   4.99   4.99   139.65
5   Wednesday       Latte          25   4.99   4.99   149.75
6    Thursday    Espresso          40   4.99   4.99   159.60
7    Thursday       Latte          30   4.99   4.99   179.70
8      Friday    Espresso          45   4.99   4.99   179.55
9      Friday       Latte          35   4.99   4.99   209.65
10   Saturday    Espresso          45   4.99   4.99   179.55
11   Saturday       Latte          35   4.99   4.99   209.65
12     Sunday    Espresso          45   4.99   4.99   179.55
13     Sunday       Latte          35   4.99   4.99   209.65

**Merging and Concatenating Data**

In [295]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [296]:
import pandas as pd
nocs = pd.read_csv('/content/data/noc_regions.csv')
print(nocs)

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

![Screenshot 2025-03-15 025943.png]()

In [297]:
bios_new=pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left', suffixes=["bios","nocdf"])#, how tells how to merge the data
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocdf,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [298]:
bios_new=bios_new.rename(columns={'region':'born_country_full'})

In [299]:
IND = bios.loc[bios['born_country']=='IND']
FRA = bios.loc[bios['born_country']=='FRA']
print(IND.head(),"\n\n\n",FRA.head())

     athlete_id                name   born_date              born_city  \
80           81      George Caridia  1869-02-20     Kolkata (Calcutta)
101         102  Algernon Kingscote  1888-02-03  Bengaluru (Bangalore)
270         271         Nora Polley  1894-07-29                 Budaun
273         274         Zeeshan Ali  1970-01-01     Kolkata (Calcutta)
274         275      Anand Amritraj  1952-03-20       Chennai (Madras)

       born_region born_country            NOC  height_cm  weight_kg  \
80     West Bengal          IND  Great Britain        NaN        NaN
101      Karnataka          IND  Great Britain        NaN        NaN
270  Uttar Pradesh          IND          India        NaN        NaN
273    West Bengal          IND          India      180.0       64.0
274     Tamil Nadu          IND          India      185.0       77.0

      died_date
80   1937-04-21
101  1964-12-21
270  1988-01-01
273         NaN
274         NaN


    athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
5           6      Nicolas Chatelain  1970-01-13       Amiens

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
5                 Somme          FRA  France      181.0       70.0         NaN

In [300]:
IND.to_parquet('/content/data/IND.parquet', index= False)
FRA.to_parquet('/content/data/FRA.parquet', index= False)

In [301]:
new_df=pd.concat([IND,FRA])
new_df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144652,148348,James Clugnet,1996-12-04,Grenoble,Isère,FRA,Great Britain,NaN,NaN,NaN
145009,148720,Margaux Hackett,1999-06-02,Annecy,Haute-Savoie,FRA,New Zealand,NaN,NaN,NaN
145281,149002,Elliott Baralo,1998-08-01,Annecy,Haute-Savoie,FRA,Sweden,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [302]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [303]:
combined_df= pd.merge(results, bios, on='athlete_id', how='left' )
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN

In [304]:
combined_df.loc[(combined_df['name'].str.contains("Michael", case = False)) & (combined_df['born_country']=='USA')]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5783,1992.0,Summer,Tennis,"Singles, Men (Olympic)",Michael Chang,2749,USA,None,17.0,True,None,Michael Chang,1972-02-22,Hoboken,New Jersey,USA,United States,175.0,72.0,NaN
5784,2000.0,Summer,Tennis,"Singles, Men (Olympic)",Michael Chang,2749,USA,None,33.0,True,None,Michael Chang,1972-02-22,Hoboken,New Jersey,USA,United States,175.0,72.0,NaN
6540,1992.0,Summer,Baseball (Baseball/Softball),"Baseball, Men (Olympic)",Michael Tucker,3251,USA,United States,4.0,False,None,Michael Tucker,1971-06-25,South Boston,Massachusetts,USA,United States,188.0,84.0,NaN
13153,1988.0,Summer,Boxing,"Light-Flyweight, Men (Olympic)",Michael Carbajal,8636,USA,None,2.0,False,Silver,Michael Carbajal,1967-09-17,Phoenix,Arizona,USA,United States,165.0,48.0,NaN
13270,1904.0,Summer,Boxing,"Heavyweight, Men (Olympic)",Bill Michaels,8733,USA,None,3.0,False,Bronze,Bill Michaels,1876-07-13,Alcoa,Tennessee,USA,United States,NaN,NaN,1934-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306041,2020.0,Summer,Rowing,"Coxless Fours, Men (Olympic)",Michael Grady,147444,USA,United States,5.0,False,None,Michael Grady,1996-10-22,Pittsburgh,Pennsylvania,USA,United States,196.0,91.0,NaN
306080,2020.0,Summer,Swimming (Aquatics),"50 metres Freestyle, Men (Olympic)",Michael Andrew,147473,USA,None,4.0,False,None,Michael Andrew,1999-04-18,Edina,Minnesota,USA,United States,NaN,NaN,NaN
306081,2020.0,Summer,Swimming (Aquatics),"100 metres Breaststroke, Men (Olympic)",Michael Andrew,147473,USA,None,4.0,False,None,Michael Andrew,1999-04-18,Edina,Minnesota,USA,United States,NaN,NaN,NaN
306082,2020.0,Summer,Swimming (Aquatics),"200 metres Individual Medley, Men (Olympic)",Michael Andrew,147473,USA,None,5.0,False,None,Michael Andrew,1999-04-18,Edina,Minnesota,USA,United States,NaN,NaN,NaN
306083,2020.0,Summer,Swimming (Aquatics),"4 × 100 metres Medley Relay, Men (Olympic)",Michael Andrew,147473,USA,United States,1.0,False,Gold,Michael Andrew,1999-04-18,Edina,Minnesota,USA,United States,NaN,NaN,NaN

In [305]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

In [306]:
coffee.head()

         Day Coffee Type  Units Sold  price  price  revenue
0     Monday    Espresso          25   4.99   4.99    99.75
1     Monday       Latte          15   4.99   4.99    89.85
2    Tuesday    Espresso          30   4.99   4.99   119.70
3    Tuesday       Latte          20   4.99   4.99   119.80
4  Wednesday    Espresso          35   4.99   4.99   139.65

In [313]:
import numpy as np
coffee.loc[[1,5], 'Units Sold'] = np.nan
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
price          0
revenue        0
dtype: int64

In [308]:
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso        25.0   4.99   4.99    99.75
1      Monday       Latte         NaN   4.99   4.99    89.85
2     Tuesday    Espresso        30.0   4.99   4.99   119.70
3     Tuesday       Latte        20.0   4.99   4.99   119.80
4   Wednesday    Espresso        35.0   4.99   4.99   139.65
5   Wednesday       Latte         NaN   4.99   4.99   149.75
6    Thursday    Espresso        40.0   4.99   4.99   159.60
7    Thursday       Latte        30.0   4.99   4.99   179.70
8      Friday    Espresso        45.0   4.99   4.99   179.55
9      Friday       Latte        35.0   4.99   4.99   209.65
10   Saturday    Espresso        45.0   4.99   4.99   179.55
11   Saturday       Latte        35.0   4.99   4.99   209.65
12     Sunday    Espresso        45.0   4.99   4.99   179.55
13     Sunday       Latte        35.0   4.99   4.99   209.65

In [318]:
#coffee = coffee.fillna(coffee['Units Sold'].mean())#fills the nan with the mean value
#coffee['Units Sold'].interpolate()
#coffee.dropna(subset=['Units Sold'])#use assingment or inplace=true
#coffee[coffee['Units Sold'].isna()]
#coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso        25.0   4.99   4.99    99.75
2     Tuesday    Espresso        30.0   4.99   4.99   119.70
3     Tuesday       Latte        20.0   4.99   4.99   119.80
4   Wednesday    Espresso        35.0   4.99   4.99   139.65
6    Thursday    Espresso        40.0   4.99   4.99   159.60
7    Thursday       Latte        30.0   4.99   4.99   179.70
8      Friday    Espresso        45.0   4.99   4.99   179.55
9      Friday       Latte        35.0   4.99   4.99   209.65
10   Saturday    Espresso        45.0   4.99   4.99   179.55
11   Saturday       Latte        35.0   4.99   4.99   209.65
12     Sunday    Espresso        45.0   4.99   4.99   179.55
13     Sunday       Latte        35.0   4.99   4.99   209.65

# **Aggregating Data**
to combine things, group things, use group table etc.

In [322]:
bios['born_city'].value_counts()
bios[bios['born_country'] =='IND']['born_region'].value_counts()

born_region
Punjab                                 94
Maharashtra                            56
West Bengal                            49
Haryana                                43
Uttar Pradesh                          42
Tamil Nadu                             34
Karnataka                              32
National Capital Territory of Delhi    32
Kerala                                 26
Andhra Pradesh                         23
Madhya Pradesh                         22
Rajasthan                              14
Manipur                                10
Himachal Pradesh                       10
Gujarat                                 9
Bihar                                   6
Jharkhand                               5
Assam                                   5
Jammu and Kashmir                       5
Uttarakhand                             4
Tripura                                 3
Chandigarh                              2
Goa                                     2
Chhattisgarh                            2
Nagaland                                2
Sikkim                                  1
Mizoram                                 1
Puducherry                              1
Orissa                                  1
Name: count, dtype: int64

In [328]:
coffee= pd.read_csv('/content/warmup_data/coffee.csv')
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [331]:
coffee['price'] = np.where(coffee['Coffee Type'] == "Espresso",3.99,5.99)

In [332]:
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   5.99
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   5.99
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   5.99
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   5.99
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   5.99
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   5.99
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   5.99

In [330]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [334]:
coffee.groupby(['Coffee Type','Day']).agg({'Units Sold': 'sum', 'price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday             45   3.99
            Monday             25   3.99
            Saturday           45   3.99
            Sunday             45   3.99
            Thursday           40   3.99
            Tuesday            30   3.99
            Wednesday          35   3.99
Latte       Friday             35   5.99
            Monday             15   5.99
            Saturday           35   5.99
            Sunday             35   5.99
            Thursday           30   5.99
            Tuesday            20   5.99
            Wednesday          25   5.99

In [333]:
coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price':'mean'})

             Units Sold  price
Coffee Type
Espresso            265   3.99
Latte               195   5.99

pivot table

In [336]:
coffee['revenue'] = coffee['Units Sold']* coffee['price']
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [339]:
pivot = coffee.pivot(columns= 'Coffee Type', index = 'Day', values='revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [341]:
pivot.loc['Monday','Latte']

89.85000000000001

In [342]:
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [343]:
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [344]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25